const tailwindColorConfig = {
  theme: {
    extend: {
      colors: {
        "background-default": "var(--background-default)",
        "background-hover": "var(--background-hover)",
        "background-active": "var(--background-active)",
        "background-selected": "var(--background-selected)",
        "background-selected-hover": "var(--background-selected-hover)",
        "background-inverse": "var(--background-inverse)",
        "background-inverse-hover": "var(--background-inverse-hover)",
        "background-brand": "var(--background-brand)",
        "background-brand-hover": "var(--background-brand-hover)",

        "layer-01": "var(--layer-01)",
        "layer-02": "var(--layer-02)",
        "layer-01-hover": "var(--layer-01-hover)",
        "layer-02-hover": "var(--layer-02-hover)",
        "layer-01-active": "var(--layer-01-active)",
        "layer-02-active": "var(--layer-02-active)",
        "layer-01-selected": "var(--layer-01-selected)",
        "layer-02-selected": "var(--layer-02-selected)",
        "layer-01-selected-hover": "var(--layer-01-selected-hover)",
        "layer-02-selected-hover": "var(--layer-02-selected-hover)",
        "layer-selected-inverse": "var(--layer-selected-inverse)",
        "layer-selected-disabled": "var(--layer-selected-disabled)",
        "layer-transparent": "var(--layer-transparent)",

        "field-01": "var(--field-01)",
        "field-02": "var(--field-02)",
        "field-01-hover": "var(--field-01-hover)",
        "field-02-hover": "var(--field-02-hover)",
        "field-inverse": "var(--field-inverse)",

        "button-primary": "var(--button-primary)",
        "button-primary-hover": "var(--button-primary-hover)",
        "button-primary-active": "var(--button-primary-active)",
        "button-secondary": "var(--button-secondary)",
        "button-secondary-hover": "var(--button-secondary-hover)",
        "button-secondary-active": "var(--button-secondary-active)",
        "button-border": "var(--button-border)",
        "button-border-hover": "var(--button-border-hover)",
        "button-border-active": "var(--button-border-active)",
        "button-danger": "var(--button-danger)",
        "button-danger-hover": "var(--button-danger-hover)",
        "button-danger-active": "var(--button-danger-active)",
        "button-disabled": "var(--button-disabled)",

        "border-subtle-01": "var(--border-subtle-01)",
        "border-subtle-02": "var(--border-subtle-02)",
        "border-subtle-selected-01": "var(--border-subtle-selected-01)",
        "border-subtle-selected-02": "var(--border-subtle-selected-02)",
        "border-strong-01": "var(--border-strong-01)",
        "border-strong-02": "var(--border-strong-02)",
        "border-strong-selected-01": "var(--border-strong-selected-01)",
        "border-strong-selected-02": "var(--border-strong-selected-02)",
        "border-error": "var(--border-error)",
        "border-tile-01": "var(--border-tile-01)",
        "border-tile-02": "var(--border-tile-02)",
        "border-inverse": "var(--border-inverse)",
        "border-disabled": "var(--border-disabled)",
        "border-interactive": "var(--border-interactive)",
        "border-transparent": "var(--border-transparent)",

        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-placeholder": "var(--text-placeholder)",
        "text-on-color": "var(--text-on-color)",
        "text-on-color-hover": "var(--text-on-color-hover)",
        "text-on-color-active": "var(--text-on-color-active)",
        "text-on-color-disabled": "var(--text-on-color-disabled)",
        "text-helper": "var(--text-helper)",
        "text-error": "var(--text-error)",
        "text-error-hover": "var(--text-error-hover)",
        "text-error-active": "var(--text-error-active)",
        "text-inverse": "var(--text-inverse)",
        "text-disabled": "var(--text-disabled)",

        "link-default": "var(--link-default)",
        "link-hover": "var(--link-hover)",
        "link-active": "var(--link-active)",
        "link-inverse": "var(--link-inverse)",
        "link-visited": "var(--link-visited)",

        "icon-primary": "var(--icon-primary)",
        "icon-secondary": "var(--icon-secondary)",
        "icon-disabled": "var(--icon-disabled)",
        "icon-on-color": "var(--icon-on-color)",
        "icon-on-color-disabled": "var(--icon-on-color-disabled)",
        "icon-interactive": "var(--icon-interactive)",
        "icon-inverse": "var(--icon-inverse)",
        "icon-error": "var(--icon-error)",

        "support-error": "var(--support-error)",
        "support-success": "var(--support-success)",
        "support-warning": "var(--support-warning)",
        "support-info": "var(--support-info)",
        "support-error-inverse": "var(--support-error-inverse)",
        "support-success-inverse": "var(--support-success-inverse)",
        "support-warning-inverse": "var(--support-warning-inverse)",
        "support-info-inverse": "var(--support-info-inverse)",

        "tag-background-disabled-gray": "var(--tag-background-disabled-gray)",
        "tag-background-black": "var(--tag-background-black)",
        "tag-border-black": "var(--tag-border-black)",
        "tag-color-black": "var(--tag-color-black)",
        "tag-hover-black": "var(--tag-hover-black)",
        "tag-icon-black": "var(--tag-icon-black)",
        "tag-background-gray": "var(--tag-background-gray)",
        "tag-border-gray": "var(--tag-border-gray)",
        "tag-color-gray": "var(--tag-color-gray)",
        "tag-hover-gray": "var(--tag-hover-gray)",
        "tag-icon-gray": "var(--tag-icon-gray)",
        "tag-background-red": "var(--tag-background-red)",
        "tag-border-red": "var(--tag-border-red)",
        "tag-color-red": "var(--tag-color-red)",
        "tag-hover-red": "var(--tag-hover-red)",
        "tag-icon-red": "var(--tag-icon-red)",
        "tag-background-orange": "var(--tag-background-orange)",
        "tag-border-orange": "var(--tag-border-orange)",
        "tag-color-orange": "var(--tag-color-orange)",
        "tag-hover-orange": "var(--tag-hover-orange)",
        "tag-icon-orange": "var(--tag-icon-orange)",
        "tag-background-yellow": "var(--tag-background-yellow)",
        "tag-border-yellow": "var(--tag-border-yellow)",
        "tag-color-yellow": "var(--tag-color-yellow)",
        "tag-hover-yellow": "var(--tag-hover-yellow)",
        "tag-icon-yellow": "var(--tag-icon-yellow)",
        "tag-background-green": "var(--tag-background-green)",
        "tag-border-green": "var(--tag-border-green)",
        "tag-color-green": "var(--tag-color-green)",
        "tag-hover-green": "var(--tag-hover-green)",
        "tag-icon-green": "var(--tag-icon-green)",
        "tag-background-blue": "var(--tag-background-blue)",
        "tag-border-blue": "var(--tag-border-blue)",
        "tag-color-blue": "var(--tag-color-blue)",
        "tag-hover-blue": "var(--tag-hover-blue)",
        "tag-icon-blue": "var(--tag-icon-blue)",
        "tag-background-cyan": "var(--tag-background-cyan)",
        "tag-border-cyan": "var(--tag-border-cyan)",
        "tag-color-cyan": "var(--tag-color-cyan)",
        "tag-hover-cyan": "var(--tag-hover-cyan)",
        "tag-icon-cyan": "var(--tag-icon-cyan)",
        "tag-background-magenta": "var(--tag-background-magenta)",
        "tag-border-magenta": "var(--tag-border-magenta)",
        "tag-color-magenta": "var(--tag-color-magenta)",
        "tag-hover-magenta": "var(--tag-hover-magenta)",
        "tag-icon-magenta": "var(--tag-icon-magenta)",
        "tag-background-purple": "var(--tag-background-purple)",
        "tag-border-purple": "var(--tag-border-purple)",
        "tag-color-purple": "var(--tag-color-purple)",
        "tag-hover-purple": "var(--tag-hover-purple)",
        "tag-icon-purple": "var(--tag-icon-purple)",
        "tag-background-teal": "var(--tag-background-teal)",
        "tag-border-teal": "var(--tag-border-teal)",
        "tag-color-teal": "var(--tag-color-teal)",
        "tag-hover-teal": "var(--tag-hover-teal)",
        "tag-icon-teal": "var(--tag-icon-teal)",
        "tag-background-outline": "var(--tag-background-outline)",
        "tag-color-outline": "var(--tag-color-outline)",
        "tag-border-outline": "var(--tag-border-outline)",
        "tag-hover-outline": "var(--tag-hover-outline)",
        "tag-icon-outline": "var(--tag-icon-outline)",

        "focus-default": "var(--focus-default)",
        "focus-inverse": "var(--focus-inverse)",

        "interactive-default": "var(--interactive-default)",
        "overlay-default": "var(--overlay-default)",
        "skeleton-container": "var(--skeleton-container)",
        "skeleton-element": "var(--skeleton-element)",
      },
    },
  },
};

export default tailwindColorConfig;
